version: "3"

services: 
  node1:
    container_name: "node1"
    image: chain 
    ports:
      - "9000-9002": "9000-9002"
    environment:
      - LOG_LEVEL=info
        SEED="node2:9000"
  node2:
    container_name: "node2"
    image: chain 
    ports:
      - "9000-9002": "9000-9002"
    environment:
      - LOG_LEVEL=info
        SEED="node1:9000"
