INSERT INTO blocks
    (
    hash,
    height,
    prevBlockHash,
    merkleRoot,
    extraNonce,
    timestamp,
    bits,
    nonce,
    transactions,
    txCount
    )
VALUES
    (
        :hash,
        :height,
        :prevBlockHash,
        :merkleRoot,
        :extraNonce,
        :timestamp,
        :bits,
        :nonce,
        :transactions,
        :txCount
   );