version: 0.1

configurations:
  log:
    log_file: gochain.log
    default_log_level: info
  chain_info:
    chain_id: 2020
  miner:
    secret_key_str: 39726aa1f7746a0a91ed31dbc36403c95f96892d8b176112570141600141545f
  db:
    db_path: ./data/blockchain.db
    driver: sqlite3
    user:
    password:
  network:
    rpc_port: 9000
    http_port: 9001
    websocket_port: 9002
