version: 0.1

configurations:
  log:
    log_file: gochain.log
    default_log_level: info
  chain_info:
    chain_id: 2020
  miner:
    secret_key_str: 58898c79caf4a77a4aa10b4b9bad7d07f7e7c1842204be352a65d87f71277137
  db:
    db_path: ./data/blockchain.db
    driver: sqlite3
    user:
    password:
  network:
    rpc:
      port: 9000
      enabled: false
    http:
      port: 9001
      enabled: true
    websocket:
      port: 9002
      enabled: false
